/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Mcl_Util;
import javax.swing.JOptionPane;
import bean.MclVendedor;
import dao.DaoGeneric;


/**
 *
 * @author u42165518822
 */
public class JDlgMcl_Vendedor extends javax.swing.JDialog {

    private String acao = "incluir";
    DaoGeneric vendedordao = new DaoGeneric();
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgMcl_Vendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);   
        habilitar(false);
    }
    
    public void habilitar(){
        Mcl_Util.mcl_habilitar(true, 
        jTxtCodigo,
        jTxtEndereco,
        jTxtNota,
        jTxtNome,
        jFmtCnpj,
        jTxtSaldo,
        jTxtVendasTotais,
        
        jBtnConfirmar,
        jBtnCancelar,
        jBtnIncluir);
    }
    public void habilitar(boolean value){
        Mcl_Util.mcl_habilitar(value,
        jTxtCodigo,
        jTxtEndereco,
        jTxtNota,
        jTxtNome,
        jFmtCnpj,
        jTxtSaldo,
        jTxtVendasTotais,
        
        jBtnConfirmar,
        jBtnCancelar,
        jBtnExcluir,
        jBtnAlterar);
    }
    
    public void limpar(){
        Mcl_Util.mcl_limpar(
        jTxtCodigo,
        jTxtEndereco,
        jTxtNota,
        jTxtNome,
        jFmtCnpj,
        jTxtSaldo,
        jTxtVendasTotais);
    }
    
    public void beanView(MclVendedor vendedor){
        
        Mcl_Util.mcl_habilitar(false, jBtnIncluir);
        Mcl_Util.mcl_habilitar(true, jBtnAlterar, jBtnExcluir, jBtnCancelar);
        
        jTxtCodigo.setText(Mcl_Util.intToStr(vendedor.getMclIdVendedor()));
        jTxtEndereco.setText(vendedor.getMclEndereco());
        jTxtNota.setText(Mcl_Util.intToStr(vendedor.getMclNota()));
        jTxtNome.setText(vendedor.getMclNome());
        jFmtCnpj.setText(vendedor.getMclCnpj());
        jTxtSaldo.setText(Mcl_Util.doubleToStr(vendedor.getMclSaldo()));
        jTxtVendasTotais.setText(Mcl_Util.intToStr(vendedor.getMclVendastotais()));
    }
    
    public MclVendedor viewBean() {
        MclVendedor vendedor = new MclVendedor();
        vendedor.setMclCnpj(jFmtCnpj.getText());
        vendedor.setMclIdVendedor(Mcl_Util.strToInt(jTxtCodigo.getText()));
        vendedor.setMclEndereco(jTxtEndereco.getText());
        vendedor.setMclNome(jTxtNome.getText());
        vendedor.setMclNota(Mcl_Util.strToInt(jTxtNota.getText()));
        vendedor.setMclSaldo(Mcl_Util.strToDouble(jTxtSaldo.getText()));
        vendedor.setMclVendastotais(Mcl_Util.strToInt(jTxtVendasTotais.getText()));
        return vendedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLblCodigo = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLblHora = new javax.swing.JLabel();
        jLblTipo = new javax.swing.JLabel();
        jTxtEndereco = new javax.swing.JTextField();
        jLblNota = new javax.swing.JLabel();
        jLblFotoUrl = new javax.swing.JLabel();
        jLblFkProduto = new javax.swing.JLabel();
        jLblFkUsuario = new javax.swing.JLabel();
        jTxtNota = new javax.swing.JTextField();
        jTxtVendasTotais = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtSaldo = new javax.swing.JTextField();
        jFmtCnpj = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLblCodigo.setText("Código");

        jTxtCodigo.setEnabled(false);

        jLblHora.setText("Nome");

        jLblTipo.setText("Endereço");

        jTxtEndereco.setEnabled(false);

        jLblNota.setText("Nota (0-10)");

        jLblFotoUrl.setText("CNPJ");

        jLblFkProduto.setText("Saldo");

        jLblFkUsuario.setText("Vendas totais");

        jTxtNota.setEnabled(false);

        jTxtVendasTotais.setEnabled(false);

        jTxtNome.setEnabled(false);

        jTxtSaldo.setEnabled(false);

        try {
            jFmtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtCnpj.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtNome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCodigo)
                                    .addComponent(jLblHora)
                                    .addComponent(jLblTipo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblNota)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLblFotoUrl))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jFmtCnpj))
                                        .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtVendasTotais)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblFkUsuario)
                                            .addComponent(jLblFkProduto))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTxtSaldo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(jBtnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTipo)
                    .addComponent(jLblFkUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVendasTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNota)
                    .addComponent(jLblFotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFkProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Mcl_Util.mcl_habilitar(true, jBtnIncluir, jBtnPesquisar);
        limpar();
        habilitar(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        acao = "incluir";
        jTxtCodigo.requestFocusInWindow();
        habilitar();
        Mcl_Util.mcl_habilitar(false, jBtnIncluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        habilitar(false);        
        try{
            if("incluir".equals(acao)) {
                vendedordao.insert(viewBean());
            } else if("alterar".equals(acao)) {
                vendedordao.update(viewBean());
            }
            Mcl_Util.tocarSom("https://host.killerfish.co/api/download/defokofoFtGekd9R");
        } catch(Throwable e) {
            Mcl_Util.tocarSom("https://host.killerfish.co/api/download/defokoQ8Z4YRm4Vh");
            Mcl_Util.mcl_mensagem(e.toString());
        }
        limpar();
        Mcl_Util.mcl_habilitar(true, jBtnIncluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        acao = "alterar";
        habilitar();
        Mcl_Util.mcl_habilitar(false, jTxtCodigo, jBtnIncluir);
        jTxtNome.requestFocusInWindow();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (Mcl_Util.mcl_confirmar("Deseja excluir?")) {
            try{
                vendedordao.delete(viewBean());
                Mcl_Util.tocarSom("https://host.killerfish.co/api/download/defokofoFtGekd9R");
            } catch(Throwable e) {
                Mcl_Util.tocarSom("https://host.killerfish.co/api/download/defokoQ8Z4YRm4Vh");
                Mcl_Util.mcl_mensagem(e.toString());
            }
            limpar();
            jBtnCancelarActionPerformed(evt);
        } else {
            Mcl_Util.mcl_habilitar(true, 
            jBtnAlterar,
            jBtnExcluir,
            jBtnCancelar
            );
            Mcl_Util.mcl_habilitar(false, jBtnIncluir);
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgMcl_VendedorPesquisar jDlgMcl_VendedorPesquisar = new JDlgMcl_VendedorPesquisar(null, true);
        jDlgMcl_VendedorPesquisar.setTelaPai(this);
        jDlgMcl_VendedorPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgMcl_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgMcl_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgMcl_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgMcl_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgMcl_Vendedor dialog = new JDlgMcl_Vendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtCnpj;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblFkProduto;
    private javax.swing.JLabel jLblFkUsuario;
    private javax.swing.JLabel jLblFotoUrl;
    private javax.swing.JLabel jLblHora;
    private javax.swing.JLabel jLblNota;
    private javax.swing.JLabel jLblTipo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNota;
    private javax.swing.JTextField jTxtSaldo;
    private javax.swing.JTextField jTxtVendasTotais;
    // End of variables declaration//GEN-END:variables
}
