package bean;
// Generated Oct 11, 2025 4:04:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MclClientes generated by hbm2java
 */
@Entity
@Table(name="mcl_clientes"
    ,catalog="db_matheus_leonel"
)
public class MclClientes  implements java.io.Serializable {


     private int mclIdClientes;
     private String mclNome;
     private String mclApelido;
     private String mclCpf;
     private String mclRg;
     private Date mclDataNascimento;
     private String mclCelular;
     private String mclEmail;
     private String mclEndereco;
     private String mclBairro;
     private String mclCidade;
     private String mclCep;
     private int mclAtivo;
     private String mclNivel;
     private String mclSexo;

    public MclClientes() {
    }

	
    public MclClientes(int mclIdClientes, String mclNome, String mclApelido, String mclCpf, String mclRg, String mclCelular, String mclEmail, String mclEndereco, String mclBairro, String mclCidade, String mclCep, int mclAtivo, String mclNivel, String mclSexo) {
        this.mclIdClientes = mclIdClientes;
        this.mclNome = mclNome;
        this.mclApelido = mclApelido;
        this.mclCpf = mclCpf;
        this.mclRg = mclRg;
        this.mclCelular = mclCelular;
        this.mclEmail = mclEmail;
        this.mclEndereco = mclEndereco;
        this.mclBairro = mclBairro;
        this.mclCidade = mclCidade;
        this.mclCep = mclCep;
        this.mclAtivo = mclAtivo;
        this.mclNivel = mclNivel;
        this.mclSexo = mclSexo;
    }
    public MclClientes(int mclIdClientes, String mclNome, String mclApelido, String mclCpf, String mclRg, Date mclDataNascimento, String mclCelular, String mclEmail, String mclEndereco, String mclBairro, String mclCidade, String mclCep, int mclAtivo, String mclNivel, String mclSexo) {
       this.mclIdClientes = mclIdClientes;
       this.mclNome = mclNome;
       this.mclApelido = mclApelido;
       this.mclCpf = mclCpf;
       this.mclRg = mclRg;
       this.mclDataNascimento = mclDataNascimento;
       this.mclCelular = mclCelular;
       this.mclEmail = mclEmail;
       this.mclEndereco = mclEndereco;
       this.mclBairro = mclBairro;
       this.mclCidade = mclCidade;
       this.mclCep = mclCep;
       this.mclAtivo = mclAtivo;
       this.mclNivel = mclNivel;
       this.mclSexo = mclSexo;
    }
   
     @Id 

    
    @Column(name="mcl_id_clientes", unique=true, nullable=false)
    public int getMclIdClientes() {
        return this.mclIdClientes;
    }
    
    public void setMclIdClientes(int mclIdClientes) {
        this.mclIdClientes = mclIdClientes;
    }

    
    @Column(name="mcl_nome", nullable=false, length=100)
    public String getMclNome() {
        return this.mclNome;
    }
    
    public void setMclNome(String mclNome) {
        this.mclNome = mclNome;
    }

    
    @Column(name="mcl_apelido", nullable=false, length=45)
    public String getMclApelido() {
        return this.mclApelido;
    }
    
    public void setMclApelido(String mclApelido) {
        this.mclApelido = mclApelido;
    }

    
    @Column(name="mcl_cpf", nullable=false, length=15)
    public String getMclCpf() {
        return this.mclCpf;
    }
    
    public void setMclCpf(String mclCpf) {
        this.mclCpf = mclCpf;
    }

    
    @Column(name="mcl_rg", nullable=false, length=16)
    public String getMclRg() {
        return this.mclRg;
    }
    
    public void setMclRg(String mclRg) {
        this.mclRg = mclRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcl_dataNascimento", length=10)
    public Date getMclDataNascimento() {
        return this.mclDataNascimento;
    }
    
    public void setMclDataNascimento(Date mclDataNascimento) {
        this.mclDataNascimento = mclDataNascimento;
    }

    
    @Column(name="mcl_celular", nullable=false, length=16)
    public String getMclCelular() {
        return this.mclCelular;
    }
    
    public void setMclCelular(String mclCelular) {
        this.mclCelular = mclCelular;
    }

    
    @Column(name="mcl_email", nullable=false, length=100)
    public String getMclEmail() {
        return this.mclEmail;
    }
    
    public void setMclEmail(String mclEmail) {
        this.mclEmail = mclEmail;
    }

    
    @Column(name="mcl_endereco", nullable=false, length=100)
    public String getMclEndereco() {
        return this.mclEndereco;
    }
    
    public void setMclEndereco(String mclEndereco) {
        this.mclEndereco = mclEndereco;
    }

    
    @Column(name="mcl_bairro", nullable=false, length=100)
    public String getMclBairro() {
        return this.mclBairro;
    }
    
    public void setMclBairro(String mclBairro) {
        this.mclBairro = mclBairro;
    }

    
    @Column(name="mcl_cidade", nullable=false, length=45)
    public String getMclCidade() {
        return this.mclCidade;
    }
    
    public void setMclCidade(String mclCidade) {
        this.mclCidade = mclCidade;
    }

    
    @Column(name="mcl_cep", nullable=false, length=10)
    public String getMclCep() {
        return this.mclCep;
    }
    
    public void setMclCep(String mclCep) {
        this.mclCep = mclCep;
    }

    
    @Column(name="mcl_ativo", nullable=false)
    public int getMclAtivo() {
        return this.mclAtivo;
    }
    
    public void setMclAtivo(int mclAtivo) {
        this.mclAtivo = mclAtivo;
    }

    
    @Column(name="mcl_nivel", nullable=false, length=45)
    public String getMclNivel() {
        return this.mclNivel;
    }
    
    public void setMclNivel(String mclNivel) {
        this.mclNivel = mclNivel;
    }

    
    @Column(name="mcl_sexo", nullable=false, length=1)
    public String getMclSexo() {
        return this.mclSexo;
    }
    
    public void setMclSexo(String mclSexo) {
        this.mclSexo = mclSexo;
    }

}


