package bean;
// Generated Oct 11, 2025 4:04:59 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MclProdutos generated by hbm2java
 */
@Entity
@Table(name="mcl_produtos"
    ,catalog="db_matheus_leonel"
)
public class MclProdutos  implements java.io.Serializable {


     private int mclIdProdutos;
     private MclVendedor mclVendedor;
     private String mclFabricante;
     private String mclModelo;
     private int mclAno;
     private String mclMatricula;
     private int mclHorasvoo;
     private String mclDescricao;
     private double mclPreco;
     private int mclEmestoque;

    public MclProdutos() {
    }

    public MclProdutos(int mclIdProdutos, MclVendedor mclVendedor, String mclFabricante, String mclModelo, int mclAno, String mclMatricula, int mclHorasvoo, String mclDescricao, double mclPreco, int mclEmestoque) {
       this.mclIdProdutos = mclIdProdutos;
       this.mclVendedor = mclVendedor;
       this.mclFabricante = mclFabricante;
       this.mclModelo = mclModelo;
       this.mclAno = mclAno;
       this.mclMatricula = mclMatricula;
       this.mclHorasvoo = mclHorasvoo;
       this.mclDescricao = mclDescricao;
       this.mclPreco = mclPreco;
       this.mclEmestoque = mclEmestoque;
    }
   
     @Id 

    
    @Column(name="mcl_id_produtos", unique=true, nullable=false)
    public int getMclIdProdutos() {
        return this.mclIdProdutos;
    }
    
    public void setMclIdProdutos(int mclIdProdutos) {
        this.mclIdProdutos = mclIdProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcl_fk_vendedor", nullable=false)
    public MclVendedor getMclVendedor() {
        return this.mclVendedor;
    }
    
    public void setMclVendedor(MclVendedor mclVendedor) {
        this.mclVendedor = mclVendedor;
    }

    
    @Column(name="mcl_fabricante", nullable=false, length=45)
    public String getMclFabricante() {
        return this.mclFabricante;
    }
    
    public void setMclFabricante(String mclFabricante) {
        this.mclFabricante = mclFabricante;
    }

    
    @Column(name="mcl_modelo", nullable=false, length=45)
    public String getMclModelo() {
        return this.mclModelo;
    }
    
    public void setMclModelo(String mclModelo) {
        this.mclModelo = mclModelo;
    }

    
    @Column(name="mcl_ano", nullable=false)
    public int getMclAno() {
        return this.mclAno;
    }
    
    public void setMclAno(int mclAno) {
        this.mclAno = mclAno;
    }

    
    @Column(name="mcl_matricula", nullable=false, length=45)
    public String getMclMatricula() {
        return this.mclMatricula;
    }
    
    public void setMclMatricula(String mclMatricula) {
        this.mclMatricula = mclMatricula;
    }

    
    @Column(name="mcl_horasvoo", nullable=false)
    public int getMclHorasvoo() {
        return this.mclHorasvoo;
    }
    
    public void setMclHorasvoo(int mclHorasvoo) {
        this.mclHorasvoo = mclHorasvoo;
    }

    
    @Column(name="mcl_descricao", nullable=false, length=100)
    public String getMclDescricao() {
        return this.mclDescricao;
    }
    
    public void setMclDescricao(String mclDescricao) {
        this.mclDescricao = mclDescricao;
    }

    
    @Column(name="mcl_preco", nullable=false, precision=17)
    public double getMclPreco() {
        return this.mclPreco;
    }
    
    public void setMclPreco(double mclPreco) {
        this.mclPreco = mclPreco;
    }

    
    @Column(name="mcl_emestoque", nullable=false)
    public int getMclEmestoque() {
        return this.mclEmestoque;
    }
    
    public void setMclEmestoque(int mclEmestoque) {
        this.mclEmestoque = mclEmestoque;
    }




}


