package bean;
// Generated 26/11/2025 14:53:23 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MclUsuarios generated by hbm2java
 */
@Entity
@Table(name="mcl_usuarios"
    ,catalog="db_matheus_leonel"
)
public class MclUsuarios  implements java.io.Serializable {


     private int mclIdUsuarios;
     private String mclNome;
     private String mclApelido;
     private String mclCpf;
     private Date mclDataNascimento;
     private int mclAtivo;
     private String mclNivel;
     private String mclSenha;

    public MclUsuarios() {
    }

	
    public MclUsuarios(int mclIdUsuarios, String mclNome, String mclApelido, String mclCpf, int mclAtivo, String mclNivel, String mclSenha) {
        this.mclIdUsuarios = mclIdUsuarios;
        this.mclNome = mclNome;
        this.mclApelido = mclApelido;
        this.mclCpf = mclCpf;
        this.mclAtivo = mclAtivo;
        this.mclNivel = mclNivel;
        this.mclSenha = mclSenha;
    }
    public MclUsuarios(int mclIdUsuarios, String mclNome, String mclApelido, String mclCpf, Date mclDataNascimento, int mclAtivo, String mclNivel, String mclSenha) {
       this.mclIdUsuarios = mclIdUsuarios;
       this.mclNome = mclNome;
       this.mclApelido = mclApelido;
       this.mclCpf = mclCpf;
       this.mclDataNascimento = mclDataNascimento;
       this.mclAtivo = mclAtivo;
       this.mclNivel = mclNivel;
       this.mclSenha = mclSenha;
    }
   
     @Id 

    
    @Column(name="mcl_id_usuarios", unique=true, nullable=false)
    public int getMclIdUsuarios() {
        return this.mclIdUsuarios;
    }
    
    public void setMclIdUsuarios(int mclIdUsuarios) {
        this.mclIdUsuarios = mclIdUsuarios;
    }

    
    @Column(name="mcl_nome", nullable=false, length=100)
    public String getMclNome() {
        return this.mclNome;
    }
    
    public void setMclNome(String mclNome) {
        this.mclNome = mclNome;
    }

    
    @Column(name="mcl_apelido", nullable=false, length=45)
    public String getMclApelido() {
        return this.mclApelido;
    }
    
    public void setMclApelido(String mclApelido) {
        this.mclApelido = mclApelido;
    }

    
    @Column(name="mcl_cpf", nullable=false, length=15)
    public String getMclCpf() {
        return this.mclCpf;
    }
    
    public void setMclCpf(String mclCpf) {
        this.mclCpf = mclCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcl_dataNascimento", length=10)
    public Date getMclDataNascimento() {
        return this.mclDataNascimento;
    }
    
    public void setMclDataNascimento(Date mclDataNascimento) {
        this.mclDataNascimento = mclDataNascimento;
    }

    
    @Column(name="mcl_ativo", nullable=false)
    public int getMclAtivo() {
        return this.mclAtivo;
    }
    
    public void setMclAtivo(int mclAtivo) {
        this.mclAtivo = mclAtivo;
    }

    
    @Column(name="mcl_nivel", nullable=false, length=45)
    public String getMclNivel() {
        return this.mclNivel;
    }
    
    public void setMclNivel(String mclNivel) {
        this.mclNivel = mclNivel;
    }

    
    @Column(name="mcl_senha", nullable=false, length=100)
    public String getMclSenha() {
        return this.mclSenha;
    }
    
    public void setMclSenha(String mclSenha) {
        this.mclSenha = mclSenha;
    }

    @Override
    public String toString() {
        return this.getMclNome();
    }

    @Override
    public boolean equals(Object bean) {
        return bean instanceof MclUsuarios && this.getMclIdUsuarios() == ((MclUsuarios) bean).getMclIdUsuarios();    
    }


}


