package bean;
// Generated Oct 11, 2025 2:20:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MclVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="mcl_vendas_produtos"
    ,catalog="db_matheus_leonel"
)
public class MclVendasProdutos  implements java.io.Serializable {


     private int mclIdVendasProdutos;
     private int mclQuantidade;
     private double mclValorunit;
     private int mclFkVendas;
     private int mclFkProdutos;

    public MclVendasProdutos() {
    }

    public MclVendasProdutos(int mclIdVendasProdutos, int mclQuantidade, double mclValorunit, int mclFkVendas, int mclFkProdutos) {
       this.mclIdVendasProdutos = mclIdVendasProdutos;
       this.mclQuantidade = mclQuantidade;
       this.mclValorunit = mclValorunit;
       this.mclFkVendas = mclFkVendas;
       this.mclFkProdutos = mclFkProdutos;
    }
   
     @Id 

    
    @Column(name="mcl_id_vendas_produtos", unique=true, nullable=false)
    public int getMclIdVendasProdutos() {
        return this.mclIdVendasProdutos;
    }
    
    public void setMclIdVendasProdutos(int mclIdVendasProdutos) {
        this.mclIdVendasProdutos = mclIdVendasProdutos;
    }

    
    @Column(name="mcl_quantidade", nullable=false)
    public int getMclQuantidade() {
        return this.mclQuantidade;
    }
    
    public void setMclQuantidade(int mclQuantidade) {
        this.mclQuantidade = mclQuantidade;
    }

    
    @Column(name="mcl_valorunit", nullable=false, precision=20)
    public double getMclValorunit() {
        return this.mclValorunit;
    }
    
    public void setMclValorunit(double mclValorunit) {
        this.mclValorunit = mclValorunit;
    }

    
    @Column(name="mcl_fk_vendas", nullable=false)
    public int getMclFkVendas() {
        return this.mclFkVendas;
    }
    
    public void setMclFkVendas(int mclFkVendas) {
        this.mclFkVendas = mclFkVendas;
    }

    
    @Column(name="mcl_fk_produtos", nullable=false)
    public int getMclFkProdutos() {
        return this.mclFkProdutos;
    }
    
    public void setMclFkProdutos(int mclFkProdutos) {
        this.mclFkProdutos = mclFkProdutos;
    }




}


