package bean;
// Generated 26/11/2025 14:53:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MclVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="mcl_vendas_produtos"
    ,catalog="db_matheus_leonel"
)
public class MclVendasProdutos  implements java.io.Serializable {


     private int mclIdVendasProdutos;
     private MclProdutos mclProdutos;
     private MclVendas mclVendas;
     private int mclQuantidade;
     private double mclValorunit;

    public MclVendasProdutos() {
    }

    public MclVendasProdutos(MclProdutos mclProdutos, MclVendas mclVendas, int mclQuantidade, double mclValorunit) {
       this.mclProdutos = mclProdutos;
       this.mclVendas = mclVendas;
       this.mclQuantidade = mclQuantidade;
       this.mclValorunit = mclValorunit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mcl_id_vendas_produtos", unique=true, nullable=false)
    public int getMclIdVendasProdutos() {
        return this.mclIdVendasProdutos;
    }
    
    public void setMclIdVendasProdutos(int mclIdVendasProdutos) {
        this.mclIdVendasProdutos = mclIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcl_fk_produtos", nullable=false)
    public MclProdutos getMclProdutos() {
        return this.mclProdutos;
    }
    
    public void setMclProdutos(MclProdutos mclProdutos) {
        this.mclProdutos = mclProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcl_fk_vendas", nullable=false)
    public MclVendas getMclVendas() {
        return this.mclVendas;
    }
    
    public void setMclVendas(MclVendas mclVendas) {
        this.mclVendas = mclVendas;
    }

    
    @Column(name="mcl_quantidade", nullable=false)
    public int getMclQuantidade() {
        return this.mclQuantidade;
    }
    
    public void setMclQuantidade(int mclQuantidade) {
        this.mclQuantidade = mclQuantidade;
    }

    
    @Column(name="mcl_valorunit", nullable=false, precision=20)
    public double getMclValorunit() {
        return this.mclValorunit;
    }
    
    public void setMclValorunit(double mclValorunit) {
        this.mclValorunit = mclValorunit;
    }
    @Override
    public boolean equals(Object bean) {
        return bean instanceof MclVendasProdutos && this.getMclIdVendasProdutos()== ((MclVendasProdutos) bean).getMclIdVendasProdutos();    
    }



}


