package bean;
// Generated Oct 11, 2025 2:20:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MclVendas generated by hbm2java
 */
@Entity
@Table(name="mcl_vendas"
    ,catalog="db_matheus_leonel"
)
public class MclVendas  implements java.io.Serializable {


     private int mclIdVendas;
     private MclClientes mclClientes;
     private MclVendedor mclVendedor;
     private Date mclDataVenda;
     private double mclTotal;

    public MclVendas() {
    }

    public MclVendas(int mclIdVendas, MclClientes mclClientes, MclVendedor mclVendedor, Date mclDataVenda, double mclTotal) {
       this.mclIdVendas = mclIdVendas;
       this.mclClientes = mclClientes;
       this.mclVendedor = mclVendedor;
       this.mclDataVenda = mclDataVenda;
       this.mclTotal = mclTotal;
    }
   
     @Id 

    
    @Column(name="mcl_id_vendas", unique=true, nullable=false)
    public int getMclIdVendas() {
        return this.mclIdVendas;
    }
    
    public void setMclIdVendas(int mclIdVendas) {
        this.mclIdVendas = mclIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcl_fk_clientes", nullable=false)
    public MclClientes getMclClientes() {
        return this.mclClientes;
    }
    
    public void setMclClientes(MclClientes mclClientes) {
        this.mclClientes = mclClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mcl_fk_vendedor", nullable=false)
    public MclVendedor getMclVendedor() {
        return this.mclVendedor;
    }
    
    public void setMclVendedor(MclVendedor mclVendedor) {
        this.mclVendedor = mclVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mcl_dataVenda", nullable=false, length=10)
    public Date getMclDataVenda() {
        return this.mclDataVenda;
    }
    
    public void setMclDataVenda(Date mclDataVenda) {
        this.mclDataVenda = mclDataVenda;
    }

    
    @Column(name="mcl_total", nullable=false, precision=20)
    public double getMclTotal() {
        return this.mclTotal;
    }
    
    public void setMclTotal(double mclTotal) {
        this.mclTotal = mclTotal;
    }




}


