package bean;
// Generated Oct 11, 2025 4:04:59 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MclVendedor generated by hbm2java
 */
@Entity
@Table(name="mcl_vendedor"
    ,catalog="db_matheus_leonel"
)
public class MclVendedor  implements java.io.Serializable {


     private int mclIdVendedor;
     private String mclNome;
     private String mclCnpj;
     private String mclEndereco;
     private int mclNota;
     private double mclSaldo;
     private int mclVendastotais;

    public MclVendedor() {
    }

	
    public MclVendedor(int mclIdVendedor, String mclNome, String mclCnpj, String mclEndereco, int mclNota, double mclSaldo, int mclVendastotais) {
        this.mclIdVendedor = mclIdVendedor;
        this.mclNome = mclNome;
        this.mclCnpj = mclCnpj;
        this.mclEndereco = mclEndereco;
        this.mclNota = mclNota;
        this.mclSaldo = mclSaldo;
        this.mclVendastotais = mclVendastotais;
    }
   
     @Id 

    
    @Column(name="mcl_id_vendedor", unique=true, nullable=false)
    public int getMclIdVendedor() {
        return this.mclIdVendedor;
    }
    
    public void setMclIdVendedor(int mclIdVendedor) {
        this.mclIdVendedor = mclIdVendedor;
    }

    
    @Column(name="mcl_nome", nullable=false, length=100)
    public String getMclNome() {
        return this.mclNome;
    }
    
    public void setMclNome(String mclNome) {
        this.mclNome = mclNome;
    }

    
    @Column(name="mcl_cnpj", nullable=false, length=20)
    public String getMclCnpj() {
        return this.mclCnpj;
    }
    
    public void setMclCnpj(String mclCnpj) {
        this.mclCnpj = mclCnpj;
    }

    
    @Column(name="mcl_endereco", nullable=false, length=100)
    public String getMclEndereco() {
        return this.mclEndereco;
    }
    
    public void setMclEndereco(String mclEndereco) {
        this.mclEndereco = mclEndereco;
    }

    
    @Column(name="mcl_nota", nullable=false)
    public int getMclNota() {
        return this.mclNota;
    }
    
    public void setMclNota(int mclNota) {
        this.mclNota = mclNota;
    }

    
    @Column(name="mcl_saldo", nullable=false, precision=20)
    public double getMclSaldo() {
        return this.mclSaldo;
    }
    
    public void setMclSaldo(double mclSaldo) {
        this.mclSaldo = mclSaldo;
    }

    
    @Column(name="mcl_vendastotais", nullable=false)
    public int getMclVendastotais() {
        return this.mclVendastotais;
    }
    
    public void setMclVendastotais(int mclVendastotais) {
        this.mclVendastotais = mclVendastotais;
    }



}


